### ISSUE TITLE
check possible bugs in code where grep matches more than it should be

### ISSUE THREAD

**Issue by janbaksay** [janvarhol/broadexec#36]
EDIT: even grep -w is not enough, see next comment.
example:
$ grep -i host1 host_file
matches
host1
but possibly:
host1
host11
host112
etc... (which is not good)

'-w' word option should resolve issue in most cases (or e.g. ^host$ if -w is not an option)
Carefully with '-c', it's just count ;)

**Comment by janbaksay** [comment]
some of the "greps" were already replaced with awk as even grep -w was not satisfactory:
$ cat servers
server1
server2
server-i1
d1-server
server3
server

$ cat servers |grep -w server
server-i1
d1-server
server

while this is expected (and can be achieved with awk):
$ cat servers | awk '($1 == "server") {print}'
server

**Comment by janvarhol** [comment]
Fixed with 0.2beta-rc1
