### ISSUE TITLE
lib.sh BRDEXEX_MISSING_KNOWN_HOSTS_SERVER or grep issue

### ISSUE THREAD

**Issue by janbaksay** [janvarhol/broadexec#38]
BRDEXEX_MISSING_KNOWN_HOSTS_SERVER is not defined 

$ ./broadexec.sh -c ./file -d /tmp -L server
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
./lib/lib.sh: line 2136: [: : integer expression expected

$ awk 'NR>=2135 && NR<=2136' ./lib/lib.sh
  if [ "$(awk '{print $1}' ~/.ssh/known_hosts 2>/dev/null | grep -wc ${BRDEXEX_MISSING_KNOWN_HOSTS_SERVER})" -eq 0 ]; then

**Comment by janvarhol** [comment]
Fixed with pull #39
